#! /bin/sh
#
# description: Set hard disk parameters
#

#
# /etc/init.d/hdparm
#

exe=/sbin/hdparm
cfg=/etc/sysconfig/hdparm

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

echo -n "hdparm - set hard disk parameters ..."

${exe} $OPTIONS 1>/dev/null
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
