#! /bin/sh
#
# description: Setup networking
#

#
# /etc/init.d/networking
#

exe=/sbin/ifup
cfg=/etc/sysconfig/networking

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

echo -n "networking - setup all interfaces ..."

# Check that networking is up.
[ "${NETWORKING}" == "no" ] && skipped && exit 0

${exe} -a
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
