#! /bin/sh
#
# description: Starts dropbear SSH daemon
#

#
# /etc/init.d/sshd
#

exe=/sbin/dropbear
cfg=/etc/sysconfig/sshd
dss=/etc/dropbear/dropbear_dss_host_key

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

echo -n "dropbear - Starts SSH daemon ........"

[ "${START}" == "no" ] && skipped && exit 0

if [ ! -f ${dss}  ]; then
 /sbin/dropbearkey -t dss -f ${dss}
fi

${exe} $OPTIONS
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
