#! /bin/sh
#
# description: Set swap parameters
#

#
# /etc/init.d/swap
#

exe=/sbin/swapon
cfg=/etc/sysconfig/swap

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

echo -n "swap - set swap partition ..........."

${exe} $OPTIONS
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
