#! /bin/sh
#
# description: Starts telnet daemon
#

#
# /etc/init.d/telnetd
#

exe=/sbin/telnetd
cfg=/etc/sysconfig/telnetd

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

echo -n "telnetd - Start telnet daemon ......."

[ "${START}" == "no" ] && skipped && exit 0

${exe} $OPTIONS
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
