#! /bin/sh
#
# description: Starts dnrd caching DNS daemon
#

#
# /etc/init.d/dns
#

exe=/sbin/dnrd
cfg=/etc/sysconfig/dns


# source function library
. /etc/init.d/functions

# source config
. ${cfg}

start() {
 echo -n "dnrd - Starts dnrd DNS Daemon ......."
 
 if [ ! -x ${exe} -o ! -f ${cfg} ]; then
  failure
  exit 1
 fi
  
 if [ "${START}" == "no" ]; then
  skipped
  exit 0
 else
  ${exe} $OPTIONS
  rc=$?

  if [ $rc -eq 0 ]; then
   success
  else
   failure
  fi
 fi
}

stop() {
 echo -n "dnrd - Stopping dnrd dns daemon ....."

 if [ ! -x ${exe} -o ! -f ${cfg} ]; then
  failure
  exit 1
 fi

 if [ "${START}" == "no" ]; then
  skipped
  exit 0
 else
  killall -q $(basename ${exe})
 fi
}

[ "$2" == "--force" ] && START=yes

case "$1" in
 start)
  start
  ;;
 stop)
  stop
  ;;
 reload)
  killall -q -SIGHUP dnrd
  ;;
 status)
  _status
  ;;
 *)
  echo "Usage: $0 {start [--force]|stop [--force]|reload|status}"
esac

exit $rc
