#! /bin/sh
#
# description: Set machine's hostname
#

#
# /etc/init.d/hostname
#

exe=/bin/hostname
cfg=/etc/hostname

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

echo -n "hostname - set machine's hostname ..."

${exe} -F ${cfg}
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
