#! /bin/sh
#
# description: Starts http daemon
#

#
# /etc/init.d/httpd
#

exe=/sbin/httpd
cfg=/etc/sysconfig/httpd

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

start() {
 echo -n "httpd - Start http daemon ..........."

 if [ ! -x ${exe} -o ! -f ${cfg} ]; then
  failure
  exit 1
 fi
 
 if [ "${START}" == "no" ]; then
  skipped
  exit 0
 else 
  if [ "$OPTIONS" == "" ]; then
   DOCROOT=/www
   [ -r /usr/www/index.html ] && DOCROOT=/usr/www
   OPTIONS="-p 80 -h $DOCROOT -r 'OpenMCT Authentication'"
  fi
 
  ${exe} $OPTIONS
  rc=$?

  if [ $rc -eq 0 ]; then
   success
  else
   failure
  fi
 fi
}

stop() {
 echo -n "httpd - Stopping http daemon ........ "

 if [ ! -x ${exe} -o ! -f ${cfg} ]; then
  failure
  exit 1
 else
  killall -q $(basename ${exe})
 fi
}

[ "$2" == "--force" ] && START=yes

case "$1" in
 start)
  start
  ;;
 stop)
  stop
  ;;
 status)
  _status
  ;;
 reload)
  killall -q -SIGHUP httpd
  ;;
 *)
  echo "Usage: $0 {start [--force]|stop [--force]|reload|status}"
esac

exit $rc
