#! /bin/sh
#
# description: Configure heardbeat LED
#

#
# /etc/init.d/heardbeat
#

hb=/proc/mct/led/hb
in=/proc/mct/led/in
out=/proc/mct/led/out
cfg=/etc/sysconfig/leds

[ ! -r ${hb} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

echo -n "leds - Configure LEDs ..............."

echo "$OPTION_HB"  > ${hb}
echo "$OPTION_IN"  > ${in}
echo "$OPTION_OUT" > ${out}
success

exit 0
