#! /bin/sh
#
# description: Setup networking
#

#
# /etc/init.d/networking
#

exe=/sbin/ifup
cfg=/etc/sysconfig/networking

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

echo -n "networking - setup all interfaces ..."

# Check that networking is up.
[ "${NETWORKING}" == "no" ] && skipped && exit 0

# Check if ip forwarding is requested
if [ "${IP_FORWARD}" == "yes" ]; then
 echo "1" > /proc/sys/net/ipv4/ip_forward
else
 echo "0" > /proc/sys/net/ipv4/ip_forward
fi

# Check if icmp echo reply is requested
if [ "${ICMP_ECHO_IGNORE_ALL}" == "yes" ]; then
 echo "1" >/proc/sys/net/ipv4/icmp_echo_ignore_all
else
 echo "0" >/proc/sys/net/ipv4/icmp_echo_ignore_all
fi

[ ! -d /usr/var/run ] && mkdir -p /usr/var/run

${exe} -a
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
