#! /bin/sh
#
# description: Starts NFS services
#

#
# /etc/init.d/nfs
#

exe=/sbin/rpc.nfsd
cfg=/etc/sysconfig/nfs

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

start() {
 echo -n "nfs - Start NFS services ............"

 [ "${START}" == "no" ] && skipped && exit 0

 [ ! -d /var/lib/nfs ] && mkdir -p /var/lib/nfs
 [ ! -d /var/run     ] && mkdir -p /var/run
 [ ! -f /var/lib/nfs/etab ] && touch /var/lib/nfs/etab
 [ ! -f /var/lib/nfs/rmtab ] && touch /var/lib/nfs/rmtab

 echo -n " rpc.mountd"
 /sbin/rpc.mountd
 rc=$?
 if [ $rc -eq 0 ]; then
  success
  sleep 1
 else
  failure
  exit $rc
 fi

 echo -n " rpc.nfsd"
 /sbin/rpc.nfsd
 rc=$?
 if [ $rc -eq 0 ]; then
  success
  sleep 1
 else
  failure
  exit $rc
 fi

 echo -n " rpc.statd"
 /sbin/rpc.statd
 rc=$?
 if [ $rc -eq 0 ]; then
  success
  sleep 1
 else
  failure
  exit $rc
 fi

 #echo -n " rpc.lockd"
 #/sbin/rpc.lockd
 #rc=$?
 #if [ $rc -eq 0 ]; then
 # success
 # sleep 1
 #else
 # failure
 # exit $rc
 #fi

 echo -n " rpc.rquotad"
 /sbin/rpc.rquotad
 rc=$?
 if [ $rc -eq 0 ]; then
  success
  sleep 1
 else
  failure
  exit $rc
 fi

 
}

stop() {
 echo -n "nfs - Stopping NFS services ............"

 if [ ! -x ${exe} -o ! -f ${cfg} ]; then
  failure
  exit 1
 else
  killall -q rpc.mountd rpc.nfsd rpc.statd rpc.lockd rpc.rquotad
 fi
}

[ "$2" == "--force" ] && START=yes

case "$1" in
 start)
  start
  ;;
 stop)
  stop
  ;;
 status)
  exe="nfsd"
  _status
  ;;
 reload)
  killall -q -SIGHUP rpc.mountd rpc.nfsd rpc.statd rpc.lockd rpc.rquotad
  ;;
 *)
  echo "Usage: $0 {start [--force]|stop [--force]|reload|status}"
esac

exit $rc
