#! /bin/sh
#
# description: Set machine's date via ntp
#

#
# /etc/init.d/ntpdate
#

exe=/sbin/ntpdate
cfg=/etc/sysconfig/ntpdate

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions
. $cfg

echo -n "ntpdate - set machines datetime ....."

${exe} $OPTIONS
rc=$?

if [ $rc -eq 0 ]; then
 success
else
 failure
fi

exit $rc
