#! /bin/sh
#
# description: Starts telnet daemon
#

#
# /etc/init.d/telnetd
#

exe=/sbin/telnetd
cfg=/etc/sysconfig/telnetd

[ ! -x ${exe} -o ! -f ${cfg} ] && exit 0

# source function library
. /etc/init.d/functions

# source config
. ${cfg}

start() {
 echo -n "telnetd - Start telnetd daemon ..........."

 [ ! -d /var/log ] && mkdir -p /var/log

 if [ ! -x ${exe} -o ! -f ${cfg} ]; then
  failure
  exit 1
 fi

 if [ "${START}" == "no" ]; then
  skipped
  exit 0
 else
  ${exe} $OPTIONS
  rc=$?

  if [ $rc -eq 0 ]; then
   success
  else
   failure
  fi
 fi
}

stop() {
 echo -n "telnetd - Stopping telnetd daemon ........ "

 if [ ! -x ${exe} -o ! -f ${cfg} ]; then
  failure
  exit 1
 else
  killall -q $(basename ${exe})
 fi
}

[ "$2" == "--force" ] && START=yes

case "$1" in
 start)
  start
  ;;
 stop)
  stop
  ;;
 status)
  _status
  ;;
 reload)
  killall -q -SIGHUP telnetd
  ;;
 *)
  echo "Usage: $0 {start [--force]|stop [--force]|reload|status}"
esac

exit $rc
