#!/bin/sh
PATH=/bin:/sbin:/var/bin

# Now run the START scripts.
for i in /etc/rc.d/rcSlocal.d/S* ; do
 $i start
done

if [ ! -f /etc/dropbear/dropbear_dss_host_key ]; then
   dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
fi

echo Starting SSH daemon
dropbear
